spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DATABASE}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    context-path: /api/v1